name: detectivce_dashboard
description: The dashboard for KKday.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  url_launcher: ^6.0.9
  provider: ^5.0.0
  syncfusion_flutter_charts: ^19.3.48
  auto_route: ^3.2.4
  flutter_staggered_grid_view: ^0.6.1
  flutter_easyloading: ^3.0.5
  url_strategy: ^0.2.0
  loadmore: ^2.0.1
  flutter_easyrefresh: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true